/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'company-admin-profile': RouteRecordInfo<'company-admin-profile', '/company/admin-profile', Record<never, never>, Record<never, never>>,
    'company-profile': RouteRecordInfo<'company-profile', '/company/profile', Record<never, never>, Record<never, never>>,
    'company-programs': RouteRecordInfo<'company-programs', '/company/programs', Record<never, never>, Record<never, never>>,
    'company-programs-id': RouteRecordInfo<'company-programs-id', '/company/programs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hacker-leaderboard': RouteRecordInfo<'hacker-leaderboard', '/hacker/leaderboard', Record<never, never>, Record<never, never>>,
    'hacker-profile': RouteRecordInfo<'hacker-profile', '/hacker/profile', Record<never, never>, Record<never, never>>,
    'hacker-programs': RouteRecordInfo<'hacker-programs', '/hacker/programs', Record<never, never>, Record<never, never>>,
    'hacker-programs-id': RouteRecordInfo<'hacker-programs-id', '/hacker/programs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'hacker-reports': RouteRecordInfo<'hacker-reports', '/hacker/reports', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
